### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by mR12KL** [jonaaa20/itunes-web-sources#14] opened 2018-11-07 22:55 UTC
Unfortunately this has stopped working again. Have gotten multiple reports. Goes straight to "No matches..."

https://ptpimg.me/g8k027.gif

**Comment by jonaaa20** [comment] 2018-11-07 23:04
Duplicate of #12, before opening a new issue, read the previous issues.

**Closed** 2018-11-07 23:04 UTC
Labels: duplicate, invalid
