### ISSUE TITLE
This script doesn't work with the latest version of Mp3Tag (2.90f)

### ISSUE THREAD

**Issue by shillshocked** [jonaaa20/itunes-web-sources#17] opened 2018-11-30 02:26 UTC
I tried using the United States script and I consistently get no results, older script from another source works fine.

**Comment by jonaaa20** [comment] 2018-11-30 06:16
Duplicate of #15, v0.3.1 is working fine.
![mp3tag_0velmyttws](https://user-images.githubusercontent.com/19306370/49271891-aeb0fe80-f456-11e8-8907-ed8134664d7d.png)

**Closed as completed** 2018-11-30 06:28 UTC
Labels: duplicate, cantreproduce

**Comment by shillshocked** [comment] 2018-12-03 11:37
Did you try on the latest version, 2.9.0f?
