### ISSUE TITLE
Script (0.3.2) doesn't work with Mp3Tag (2.91)

### ISSUE THREAD

**Issue by simonesolazzo** [jonaaa20/itunes-web-sources#19] opened 2018-12-14 15:19 UTC
It's been a few weeks since the script doesn't work for me. I'm using the latest version of Mp3Tag (2.91) and the latest version of the script (0.3.2). I tried using the Italian version and the USA version but both get no results.
![screenshot 171](https://user-images.githubusercontent.com/35707697/50011182-b4145a00-ffbb-11e8-9706-683a60fbb81e.png)
![screenshot 174](https://user-images.githubusercontent.com/35707697/50011192-bb3b6800-ffbb-11e8-8437-e58f6f291c77.png)
![screenshot 175](https://user-images.githubusercontent.com/35707697/50011206-c2fb0c80-ffbb-11e8-902c-36972158f1fe.png)

**Comment by jonaaa20** [comment] 2018-12-14 16:12
Duplicate of #15.

Please, check the **releases area**

There's a big notice message regarding 0.3.2 version, I will delete any future issues regarding this version.

**I don't support 0.3.2 for now, check the releases area.**

**Closed** 2018-12-14 16:13 UTC
